version: 2

project_name: simplestreams-s3

before:
  hooks:
    - go test ./...

builds:
  - id: simplestreams-s3
    main: ./cmd/simplestreams-s3
    binary: simplestreams-s3
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: simplestreams-s3
    ids:
      - simplestreams-s3
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

sboms:
  - id: binary
    artifacts: binary

changelog:
  disable: true

release:
  disable: true
