site_name: simplestreams-s3
site_description: Incus Simple Streams private-S3 publisher and proxy
site_url: https://meigma.github.io/simplestreams-s3/
repo_name: meigma/simplestreams-s3
repo_url: https://github.com/meigma/simplestreams-s3
edit_uri: edit/master/docs/docs/
docs_dir: docs
site_dir: build
strict: true

theme:
  name: material
  language: en
  features:
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - How-to guides:
      - Publish images: publish-images.md
      - Deploy the proxy: deploy-the-proxy.md
  - Reference:
      - Configuration: configuration.md
      - Proxy interface: proxy-interface.md
  - Explanation:
      - Design: design.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/palette.css
